#!/usr/bin/env python3
"""Write src/data/delfA1COTrain.js from the parsed S'ENTRAÎNER exercices.

    python3 scripts/delf-a1-parse-co-train.py | python3 scripts/delf-a1-gen-co-train.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "src/data/delfA1COTrain.js"

HEADER = '''// Compréhension de l'oral — S'ENTRAÎNER, « Le DELF A1 100 % réussite » p.28–37.
//
// GENERATED by scripts/delf-a1-parse-co-train.py; edit the script, not this file.
//
// These are the exam-format exercices: one document, four questions, points per
// question. Answers come from the Corrigés, which print the letter as well as
// the wording, and the generator only keeps an exercice where the two agree —
// so a parse that drifted is dropped rather than shipped with a wrong key.
//
// {kept} of the book's 15 are here. Exercices 1, 4, 7 and 10 are its worked
// examples, printed pre-ticked with no corrigés entry; 11–15 are built on
// picture matching and OUI/NON object grids that still need their artwork cut.

const piste = n => "/api/delf-audio?p=" + n;
const IMG = "/delf-a1/options";

export const CO_TRAIN = [
'''


def js(v):
    return json.dumps(v, ensure_ascii=False)


# Same five objectifs as the drills, three exercices each (p.28/30/32/34/36).
OBJECTIF_OF_EXERCICE = [(3, 1), (6, 2), (9, 3), (12, 4), (15, 5)]


def objectif(num):
    return next(o for last, o in OBJECTIF_OF_EXERCICE if num <= last)


def main():
    data = json.load(sys.stdin)
    exs = data["exercices"]
    out = [HEADER.format(kept=len(exs))]

    for e in exs:
        pts = sum(float(q["pts"] or 0) for q in e["questions"])
        out.append("  {")
        out.append(f'    id: "co-ex{e["num"]}", label: "Exercice {e["num"]}", page: {e["page"]},')
        out.append(f'    objectif: {objectif(e["num"])},')
        out.append(f'    setup: {js(e["consigne"])},')
        out.append(f'    audio: piste({e["piste"]}), piste: {e["piste"]}, pts: {pts:g},')
        out.append(f'    transcript: {js(e["transcript"])},')
        out.append("    questions: [")
        for q in e["questions"]:
            pt = f', pts: {float(q["pts"]):g}' if q.get("pts") else ""
            if q.get("kind") == "image":
                out.append(f'      {{ q: {js(q["q"])}, kind: "image",')
                out.append(f'        src: `${{IMG}}/{q["crop"]}.webp`,')
                out.append(f'        answer: {js(q["answer"])}{pt} }},')
            else:
                out.append(f'      {{ q: {js(q["q"])},')
                out.append(f'        options: {js(q["options"])},')
                out.append(f'        answer: {js(q["answer"])}{pt} }},')
        out.append("    ],")
        out.append("  },")

    out.append("];\n")
    out.append("export default CO_TRAIN;\n")
    DEST.write_text("\n".join(out))
    print(f"wrote {DEST.relative_to(ROOT)} — {len(exs)} exercices, "
          f"{sum(len(e['questions']) for e in exs)} questions", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
