#!/usr/bin/env python3
"""Write src/data/delfA1CO.js from the parsed listening drills.

    python3 scripts/delf-a1-parse-co.py | python3 scripts/delf-a1-gen-co.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "src/data/delfA1CO.js"

HEADER = '''// Compréhension de l'oral — SE PRÉPARER drills, « Le DELF A1 100 % réussite » p.12–27.
//
// GENERATED by scripts/delf-a1-parse-co.py; edit the script, not this file.
//
// Only the plain multiple-choice drills are here, and only where every answer
// the Corrigés give is one of the printed choices — an activité whose parse
// drifted is dropped rather than shipped with a wrong key. The drills built on
// matching tables, timetables or pictures (reliez…, complétez le tableau,
// notez le numéro sous l'image) need question types this screen does not have
// yet, so {kept} of the book's 58 are here so far.
//
// Audio is the book's own tracks, held in a PRIVATE Vercel Blob store and
// streamed through /api/delf-audio — they are copyrighted, so they are neither
// public assets nor committed to this repo.

export const CO_PREPARE = [
'''


def js(v):
    return json.dumps(v, ensure_ascii=False)


# The book groups the listening drills under five objectifs (p.12/14/17/20/24).
# Carrying the number lets the screen show one objectif at a time instead of a
# single scroll of 26 cards.
OBJECTIF_OF_ACTIVITE = [(13, 1), (25, 2), (36, 3), (48, 4), (58, 5)]


def objectif(num, table):
    return next(o for last, o in table if num <= last)


def main():
    data = json.load(sys.stdin)
    acts = data["activites"]
    out = [HEADER.format(kept=len(acts))]

    for a in acts:
        out.append("  {")
        out.append(f'    id: "co-a{a["num"]}", label: "Activité {a["num"]}", page: {a["page"]},')
        out.append(f'    objectif: {objectif(a["num"], OBJECTIF_OF_ACTIVITE)},')
        out.append(f'    setup: {js(a["consigne"])},')
        out.append(f'    audio: "/api/delf-audio?p={a["piste"]}", piste: {a["piste"]},')
        out.append(f'    transcript: {js(a["transcript"])},')
        out.append("    questions: [")
        for q in a["questions"]:
            lead = f'lead: {js(q["lead"])}, ' if q.get("lead") else ""
            out.append(f'      {{ {lead}q: {js(q["q"])},')
            out.append(f'        options: {js(q["options"])},')
            out.append(f'        answer: {js(q["answer"])} }},')
        out.append("    ],")
        out.append("  },")

    out.append("];\n")
    out.append("export default CO_PREPARE;\n")
    DEST.write_text("\n".join(out))
    print(f"wrote {DEST.relative_to(ROOT)} — {len(acts)} activités, "
          f"{sum(len(a['questions']) for a in acts)} questions", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
